- name: seetting up db server
  hosts: db 
  become: yes
  tasks: 
  - name: installing mysql-server
    ansible.biultin.dnf:
      name: mysql-server
      state: latest
  - name: starting and enabling db server
    ansible.builtin.service:
      name: mysql-server 
      state: started 
      enable: yes    
  - name: install python mysql dependencies
    ansible.builtin.pip:
       name:
       - PyMySQL
       - cryptography
       executable: pip3.9    
  - name: setup root password
    ansible.builtin.command: "mysql_secure_installation --set-root-pass {{ mysql_root_password }}"
    when: mysql_connection_output.failed is true # don't give {{ }} in when condition    